import assert from 'node:assert/strict'; import test from 'node:test';
import {createEvidencePacket,fingerprintCanonicalContent} from './evidence.js';
import {createResearchBundle,createAnalystReview} from './researchPipeline.js';
import {createResearchCouncilDecision} from './researchCouncil.js';
import {createThesisScenarioArtifact} from './thesisScenario.js';
import {createReportArtifact,type ReportArtifact} from './reportArtifact.js';
import {createReportExport,type ReportExportArtifact} from './reportExport.js';
import {verifyReportExportConsistency,type ReportConsistencyResult} from './reportConsistency.js';
import {createAlphaReadModel} from './alphaReadModel.js';
const now=new Date('2026-09-21T06:00:00Z');
function setup(){const mk=(id:string,txt:string)=>createEvidencePacket({evidenceId:id,source:{sourceId:id,sourceVersion:'v1',publisher:'T'},asset:{status:'RESOLVED',canonicalAssetId:'KRX:1',symbol:'1'},provenance:{retrievalUri:`https://example.test/${id}`,retrievedBy:'test'},publishedAt:'2026-09-21T04:00:00Z',observedAt:'2026-09-21T04:10:00Z',canonicalContent:txt},now);const mat=(id:string,txt:string)=>({evidenceId:id,canonicalContent:txt,contentFingerprint:fingerprintCanonicalContent(txt)});const bundle=createResearchBundle({bundleId:'b',subjectId:'KRX:1',asOf:'2026-09-21T04:30:00Z',knowledgeCutoff:'2026-09-21T04:30:00Z',items:[{evidence:mk('s','Demand improved.'),disposition:'SUPPORTING',material:mat('s','Demand improved.')},{evidence:mk('c','Margins weakened.'),disposition:'CONTRADICTING',material:mat('c','Margins weakened.')}],dataGaps:['GAP0']});const review=createAnalystReview(bundle,{reviewId:'a',bundleId:'b',analyst:{analystId:'a',role:'Analyst',domain:'company',methodVersion:'1',promptVersion:'1'},asOf:'2026-09-21T04:40:00Z',stance:'NEUTRAL',confidence:.5,assessment:'mixed',facts:[],inferences:[],assumptions:[],supportingEvidenceIds:['s'],counterevidenceIds:['c'],dataGaps:[],strongestCounterargument:'margin',invalidationConditions:[]});const council=createResearchCouncilDecision(review,{councilId:'co',analystReviewId:'a',asOf:'2026-09-21T05:00:00Z',methodVersion:'1',promptVersion:'1',specialistReviews:[],redTeamChallenges:[],stance:'INSUFFICIENT_DATA',confidence:null,synthesis:'bounded',unresolvedDisagreements:['demand vs margin'],dataGaps:['GAP1']});const scenarios=[{kind:'BULL' as const,narrative:'upside',evidenceIds:['s'],contradictingEvidenceIds:['c'],catalysts:['demand'],risks:['margin'],invalidationConditions:['demand reversal']},{kind:'BASE' as const,narrative:'mixed',evidenceIds:['s'],contradictingEvidenceIds:['c'],catalysts:[],risks:['margin'],invalidationConditions:['material change']},{kind:'BEAR' as const,narrative:'downside',evidenceIds:['c'],contradictingEvidenceIds:['c'],catalysts:[],risks:['margin'],invalidationConditions:['margin recovery']}] as const;const thesis=createThesisScenarioArtifact(bundle,review,council,{artifactId:'t1',bundleId:'b',analystReviewId:'a',councilId:'co',asOf:'2026-09-21T05:10:00Z',methodVersion:'1',thesis:'',scenarios});const report=createReportArtifact(bundle,council,thesis,{reportId:'r1',seriesId:'series',version:1,asOf:'2026-09-21T05:20:00Z',title:'BOR report',summary:'bounded summary'});const exported=createReportExport(report,{exportId:'x1',format:'PDF'});return{report,exported,consistency:verifyReportExportConsistency(report,exported)};}
test('creates deterministic no-authority projection preserving citations and uncertainty',()=>{const {report,exported,consistency}=setup();const out=createAlphaReadModel(report,exported,consistency,{projectionId:'p1'});assert.deepEqual(out.citationEvidenceIds,['c','s']);assert.equal(out.scenarios.length,3);assert.deepEqual(out.unresolvedDisagreements,['demand vs margin']);assert.deepEqual(out.dataGaps,['GAP0','GAP1']);assert.equal(out.executionAuthority,false);assert.equal(out.reportPublicationAuthority,false);assert.equal(out.botDependency,false);assert.equal(out.reportContentFingerprint,report.contentFingerprint);assert.equal(out.exportFingerprint,exported.exportFingerprint);});
test('fails closed when supplied consistency is FAIL or mismatched',()=>{const {report,exported,consistency}=setup();const failed={...consistency,status:'FAIL',issues:['CITATION_SET_MISMATCH']} as ReportConsistencyResult;assert.throws(()=>createAlphaReadModel(report,exported,failed,{projectionId:'p'}),/requires/);const wrong={...consistency,reportId:'other'} as ReportConsistencyResult;assert.throws(()=>createAlphaReadModel(report,exported,wrong,{projectionId:'p'}),/parent mismatch/);});
test('re-verifies parents and rejects tamper or authority escalation',()=>{const {report,exported,consistency}=setup();const tampered={...report,summary:'tampered'} as ReportArtifact;assert.throws(()=>createAlphaReadModel(tampered,exported,consistency,{projectionId:'p'}),/parent integrity failure/);const stale={...exported,reportVersion:2} as ReportExportArtifact;assert.throws(()=>createAlphaReadModel(report,stale,consistency,{projectionId:'p'}),/parent integrity failure/);assert.throws(()=>createAlphaReadModel(report,exported,consistency,{projectionId:'p',executionAuthority:true}),/cannot grant/);assert.throws(()=>createAlphaReadModel(report,exported,consistency,{projectionId:'p',botDependency:true}),/cannot grant/);});
