import assert from 'node:assert/strict'; import test from 'node:test';
import {createEvidencePacket,fingerprintCanonicalContent} from './evidence.js';
import {createResearchBundle,createAnalystReview} from './researchPipeline.js';
import {createResearchCouncilDecision} from './researchCouncil.js';
import {createThesisScenarioArtifact} from './thesisScenario.js';
import {createReportArtifact,type ReportArtifact} from './reportArtifact.js';
import {createReportExport,type ReportExportArtifact} from './reportExport.js';
import {verifyReportExportConsistency} from './reportConsistency.js';
const now=new Date('2026-09-21T06:00:00Z');
function pair(){const mk=(id:string,txt:string)=>createEvidencePacket({evidenceId:id,source:{sourceId:id,sourceVersion:'v1',publisher:'T'},asset:{status:'RESOLVED',canonicalAssetId:'KRX:1',symbol:'1'},provenance:{retrievalUri:`https://example.test/${id}`,retrievedBy:'test'},publishedAt:'2026-09-21T04:00:00Z',observedAt:'2026-09-21T04:10:00Z',canonicalContent:txt},now);const mat=(id:string,txt:string)=>({evidenceId:id,canonicalContent:txt,contentFingerprint:fingerprintCanonicalContent(txt)});const bundle=createResearchBundle({bundleId:'b',subjectId:'KRX:1',asOf:'2026-09-21T04:30:00Z',knowledgeCutoff:'2026-09-21T04:30:00Z',items:[{evidence:mk('s','Demand improved.'),disposition:'SUPPORTING',material:mat('s','Demand improved.')},{evidence:mk('c','Margins weakened.'),disposition:'CONTRADICTING',material:mat('c','Margins weakened.')}],dataGaps:['GAP0']});const review=createAnalystReview(bundle,{reviewId:'a',bundleId:'b',analyst:{analystId:'a',role:'Analyst',domain:'company',methodVersion:'1',promptVersion:'1'},asOf:'2026-09-21T04:40:00Z',stance:'NEUTRAL',confidence:.5,assessment:'mixed',facts:[],inferences:[],assumptions:[],supportingEvidenceIds:['s'],counterevidenceIds:['c'],dataGaps:[],strongestCounterargument:'margin',invalidationConditions:[]});const council=createResearchCouncilDecision(review,{councilId:'co',analystReviewId:'a',asOf:'2026-09-21T05:00:00Z',methodVersion:'1',promptVersion:'1',specialistReviews:[],redTeamChallenges:[],stance:'INSUFFICIENT_DATA',confidence:null,synthesis:'bounded',unresolvedDisagreements:['demand vs margin'],dataGaps:['GAP1']});const scenarios=[{kind:'BULL' as const,narrative:'upside',evidenceIds:['s'],contradictingEvidenceIds:['c'],catalysts:['demand'],risks:['margin'],invalidationConditions:['demand reversal']},{kind:'BASE' as const,narrative:'mixed',evidenceIds:['s'],contradictingEvidenceIds:['c'],catalysts:[],risks:['margin'],invalidationConditions:['material change']},{kind:'BEAR' as const,narrative:'downside',evidenceIds:['c'],contradictingEvidenceIds:['c'],catalysts:[],risks:['margin'],invalidationConditions:['margin recovery']}] as const;const thesis=createThesisScenarioArtifact(bundle,review,council,{artifactId:'t1',bundleId:'b',analystReviewId:'a',councilId:'co',asOf:'2026-09-21T05:10:00Z',methodVersion:'1',thesis:'',scenarios});const report=createReportArtifact(bundle,council,thesis,{reportId:'r1',seriesId:'series',version:1,asOf:'2026-09-21T05:20:00Z',title:'BOR report',summary:'bounded summary'});return{report,exported:createReportExport(report,{exportId:'x1',format:'PDF'})};}
test('passes an intact report/export pair with zero authority',()=>{const {report,exported}=pair();const out=verifyReportExportConsistency(report,exported);assert.equal(out.status,'PASS');assert.deepEqual(out.issues,[]);assert.equal(out.executionAuthority,false);assert.equal(out.reportPublicationAuthority,false);});
test('detects stale/tampered parent and authority escalation without repair',()=>{const {report,exported}=pair();const stale={...exported,reportVersion:2} as ReportExportArtifact;assert.deepEqual(verifyReportExportConsistency(report,stale).issues,['EXPORT_FINGERPRINT_INVALID','PARENT_IDENTITY_MISMATCH']);const elevated={...exported,reportPublicationAuthority:true} as unknown as ReportExportArtifact;assert.ok(verifyReportExportConsistency(report,elevated).issues.includes('AUTHORITY_ESCALATION'));const tampered={...report,summary:'tampered'} as ReportArtifact;assert.ok(verifyReportExportConsistency(tampered,exported).issues.includes('REPORT_FINGERPRINT_INVALID'));});
test('detects citation, scenario, disagreement and data-gap suppression',()=>{const {report,exported}=pair();const citation={...exported,citationEvidenceIds:['s']} as ReportExportArtifact;assert.ok(verifyReportExportConsistency(report,citation).issues.includes('CITATION_SET_MISMATCH'));const scenario={...exported,scenarios:exported.scenarios.slice(0,2)} as ReportExportArtifact;assert.ok(verifyReportExportConsistency(report,scenario).issues.includes('SCENARIO_MISMATCH'));const disagreement={...exported,unresolvedDisagreements:[]} as ReportExportArtifact;assert.ok(verifyReportExportConsistency(report,disagreement).issues.includes('DISAGREEMENT_MISMATCH'));const gaps={...exported,dataGaps:[]} as ReportExportArtifact;assert.ok(verifyReportExportConsistency(report,gaps).issues.includes('DATA_GAP_MISMATCH'));});
