import assert from 'node:assert/strict'; import test from 'node:test';
import {createEvidencePacket,fingerprintCanonicalContent} from './evidence.js';
import {createResearchBundle,createAnalystReview} from './researchPipeline.js';
import {createResearchCouncilDecision} from './researchCouncil.js';
import {createThesisScenarioArtifact} from './thesisScenario.js';
import {createReportArtifact,type ReportArtifact} from './reportArtifact.js';
import {createReportExport} from './reportExport.js';
const now=new Date('2026-09-21T06:00:00Z');
function report(){const mk=(id:string,txt:string)=>createEvidencePacket({evidenceId:id,source:{sourceId:id,sourceVersion:'v1',publisher:'T'},asset:{status:'RESOLVED',canonicalAssetId:'KRX:1',symbol:'1'},provenance:{retrievalUri:`https://example.test/${id}`,retrievedBy:'test'},publishedAt:'2026-09-21T04:00:00Z',observedAt:'2026-09-21T04:10:00Z',canonicalContent:txt},now);const mat=(id:string,txt:string)=>({evidenceId:id,canonicalContent:txt,contentFingerprint:fingerprintCanonicalContent(txt)});const bundle=createResearchBundle({bundleId:'b',subjectId:'KRX:1',asOf:'2026-09-21T04:30:00Z',knowledgeCutoff:'2026-09-21T04:30:00Z',items:[{evidence:mk('s','Demand improved.'),disposition:'SUPPORTING',material:mat('s','Demand improved.')},{evidence:mk('c','Margins weakened.'),disposition:'CONTRADICTING',material:mat('c','Margins weakened.')}],dataGaps:['GAP0']});const review=createAnalystReview(bundle,{reviewId:'a',bundleId:'b',analyst:{analystId:'a',role:'Analyst',domain:'company',methodVersion:'1',promptVersion:'1'},asOf:'2026-09-21T04:40:00Z',stance:'NEUTRAL',confidence:.5,assessment:'mixed',facts:[],inferences:[],assumptions:[],supportingEvidenceIds:['s'],counterevidenceIds:['c'],dataGaps:[],strongestCounterargument:'margin',invalidationConditions:[]});const council=createResearchCouncilDecision(review,{councilId:'co',analystReviewId:'a',asOf:'2026-09-21T05:00:00Z',methodVersion:'1',promptVersion:'1',specialistReviews:[],redTeamChallenges:[],stance:'INSUFFICIENT_DATA',confidence:null,synthesis:'bounded',unresolvedDisagreements:['demand vs margin'],dataGaps:['GAP1']});const scenarios=[{kind:'BULL' as const,narrative:'upside',evidenceIds:['s'],contradictingEvidenceIds:['c'],catalysts:['demand'],risks:['margin'],invalidationConditions:['demand reversal']},{kind:'BASE' as const,narrative:'mixed',evidenceIds:['s'],contradictingEvidenceIds:['c'],catalysts:[],risks:['margin'],invalidationConditions:['material change']},{kind:'BEAR' as const,narrative:'downside',evidenceIds:['c'],contradictingEvidenceIds:['c'],catalysts:[],risks:['margin'],invalidationConditions:['margin recovery']}] as const;const thesis=createThesisScenarioArtifact(bundle,review,council,{artifactId:'t1',bundleId:'b',analystReviewId:'a',councilId:'co',asOf:'2026-09-21T05:10:00Z',methodVersion:'1',thesis:'',scenarios});return createReportArtifact(bundle,council,thesis,{reportId:'r1',seriesId:'series',version:1,asOf:'2026-09-21T05:20:00Z',title:'BOR report',summary:'bounded summary'});}
test('creates deterministic export preserving report identity citations and uncertainty',()=>{const r=report();const a=createReportExport(r,{exportId:'x1',format:'PDF'});const b=createReportExport(r,{exportId:'x1',format:'PDF'});assert.equal(a.exportFingerprint,b.exportFingerprint);assert.equal(a.reportContentFingerprint,r.contentFingerprint);assert.deepEqual(a.citationEvidenceIds,r.citationEvidenceIds);assert.deepEqual(a.unresolvedDisagreements,r.unresolvedDisagreements);assert.deepEqual(a.dataGaps,r.dataGaps);assert.equal(a.executionAuthority,false);assert.equal(a.reportPublicationAuthority,false);});
test('fails closed on tampered parent and authority escalation',()=>{const r=report();assert.throws(()=>createReportExport({...r,summary:'tampered'} as ReportArtifact,{exportId:'x1',format:'HTML'}),/fingerprint mismatch/);assert.throws(()=>createReportExport(r,{exportId:'x1',format:'HTML',reportPublicationAuthority:true}),/cannot grant/);});
test('rejects unsupported format at runtime',()=>{const r=report();assert.throws(()=>createReportExport(r,{exportId:'x1',format:'DOCX' as never}),/unsupported/);});
