import assert from 'node:assert/strict'; import test from 'node:test';
import {createEvidencePacket,fingerprintCanonicalContent} from './evidence.js';
import {createResearchBundle,createAnalystReview} from './researchPipeline.js';
import {createSpecialistReview,createRedTeamChallenge,createResearchCouncilDecision} from './researchCouncil.js';
const now=new Date('2026-09-21T06:00:00Z');
function setup(){ const s='Demand improved.',c='Margins weakened.'; const ev=(id:string,txt:string)=>createEvidencePacket({evidenceId:id,source:{sourceId:id,sourceVersion:'v1',publisher:'T'},asset:{status:'RESOLVED',canonicalAssetId:'KRX:1',symbol:'1'},provenance:{retrievalUri:`https://example.test/${id}`,retrievedBy:'test'},publishedAt:'2026-09-21T04:00:00Z',observedAt:'2026-09-21T04:10:00Z',canonicalContent:txt},now); const mat=(id:string,txt:string)=>({evidenceId:id,canonicalContent:txt,contentFingerprint:fingerprintCanonicalContent(txt)}); const bundle=createResearchBundle({bundleId:'b',subjectId:'KRX:1',asOf:'2026-09-21T04:30:00Z',knowledgeCutoff:'2026-09-21T04:30:00Z',items:[{evidence:ev('s',s),disposition:'SUPPORTING',material:mat('s',s)},{evidence:ev('c',c),disposition:'CONTRADICTING',material:mat('c',c)}],dataGaps:['GAP0']}); const review=createAnalystReview(bundle,{reviewId:'a',bundleId:'b',analyst:{analystId:'a',role:'Analyst',domain:'company',methodVersion:'1',promptVersion:'1'},asOf:'2026-09-21T04:40:00Z',stance:'NEUTRAL',confidence:.6,assessment:'mixed',facts:[],inferences:[],assumptions:[],supportingEvidenceIds:['s'],counterevidenceIds:['c'],dataGaps:[],strongestCounterargument:'margin',invalidationConditions:[]}); return {bundle,review}; }
const actor={actorId:'sp',role:'Specialist',domain:'company',methodVersion:'1',promptVersion:'1'};
test('council preserves disagreement, gaps and no authority',()=>{ const {bundle,review}=setup(); const sp=createSpecialistReview(bundle,review,{reviewId:'sp1',analystReviewId:'a',actor,asOf:'2026-09-21T04:50:00Z',stance:'POSITIVE',confidence:.7,assessment:'demand',evidenceIds:['s'],dataGaps:['GAP1']}); const rt=createRedTeamChallenge(bundle,review,{challengeId:'rt1',analystReviewId:'a',actor:{...actor,actorId:'rt',role:'Red Team'},asOf:'2026-09-21T04:55:00Z',strongestCounterargument:'margin risk',contradictingEvidenceIds:['c'],unresolvedQuestions:['durability'],invalidationConditions:['margin recovery']}); const out=createResearchCouncilDecision(review,{councilId:'co1',analystReviewId:'a',asOf:'2026-09-21T05:00:00Z',methodVersion:'1',promptVersion:'1',specialistReviews:[sp],redTeamChallenges:[rt],stance:'NEUTRAL',confidence:.55,synthesis:'Evidence remains mixed.',unresolvedDisagreements:['demand vs margin']}); assert.deepEqual(out.dataGaps,['GAP0','GAP1']); assert.deepEqual(out.unresolvedDisagreements,['demand vs margin']); assert.equal(out.executionAuthority,false); assert.equal(out.reportPublicationAuthority,false); });
test('fails closed on invented evidence, wrong red-team disposition, chronology and authority',()=>{ const {bundle,review}=setup(); assert.throws(()=>createSpecialistReview(bundle,review,{reviewId:'x',analystReviewId:'a',actor,asOf:'2026-09-21T04:50:00Z',stance:'NEUTRAL',confidence:null,assessment:'x',evidenceIds:['invented']}),/outside/); assert.throws(()=>createRedTeamChallenge(bundle,review,{challengeId:'x',analystReviewId:'a',actor,asOf:'2026-09-21T04:50:00Z',strongestCounterargument:'x',contradictingEvidenceIds:['s'],unresolvedQuestions:[],invalidationConditions:[]}),/CONTRADICTING/); assert.throws(()=>createSpecialistReview(bundle,review,{reviewId:'x',analystReviewId:'a',actor,asOf:'2026-09-21T04:20:00Z',stance:'NEUTRAL',confidence:null,assessment:'x',evidenceIds:[]}),/precede/); assert.throws(()=>createSpecialistReview(bundle,review,{reviewId:'x',analystReviewId:'a',actor,asOf:'2026-09-21T04:50:00Z',stance:'NEUTRAL',confidence:null,assessment:'x',evidenceIds:[],executionAuthority:true}),/cannot grant/); });
test('council can explicitly return insufficient data',()=>{ const {review}=setup(); const out=createResearchCouncilDecision(review,{councilId:'co-gap',analystReviewId:'a',asOf:'2026-09-21T05:00:00Z',methodVersion:'1',promptVersion:'1',specialistReviews:[],redTeamChallenges:[],stance:'INSUFFICIENT_DATA',confidence:null,synthesis:'Insufficient grounded review coverage.',unresolvedDisagreements:[],dataGaps:['NO_SPECIALIST_COVERAGE']}); assert.equal(out.stance,'INSUFFICIENT_DATA'); assert.ok(out.dataGaps.includes('NO_SPECIALIST_COVERAGE')); });

test('council rejects forged member authority and unsupported empty synthesis',()=>{ const {bundle,review}=setup(); const sp=createSpecialistReview(bundle,review,{reviewId:'sp-forge',analystReviewId:'a',actor,asOf:'2026-09-21T04:50:00Z',stance:'POSITIVE',confidence:.7,assessment:'demand',evidenceIds:['s']}); const forged={...sp,executionAuthority:true} as unknown as typeof sp; assert.throws(()=>createResearchCouncilDecision(review,{councilId:'co-forge',analystReviewId:'a',asOf:'2026-09-21T05:00:00Z',methodVersion:'1',promptVersion:'1',specialistReviews:[forged],redTeamChallenges:[],stance:'NEUTRAL',confidence:.5,synthesis:'x',unresolvedDisagreements:[]}),/authority\/schema mismatch/); assert.throws(()=>createResearchCouncilDecision(review,{councilId:'co-empty',analystReviewId:'a',asOf:'2026-09-21T05:00:00Z',methodVersion:'1',promptVersion:'1',specialistReviews:[],redTeamChallenges:[],stance:'NEUTRAL',confidence:.5,synthesis:'x',unresolvedDisagreements:[]}),/empty council/); });

test('council artifacts freeze member arrays and reject unsupported runtime stances',()=>{ const {bundle,review}=setup(); const sp=createSpecialistReview(bundle,review,{reviewId:'sp-freeze',analystReviewId:'a',actor,asOf:'2026-09-21T04:50:00Z',stance:'POSITIVE',confidence:.7,assessment:'demand',evidenceIds:['s']}); const members=[sp]; const out=createResearchCouncilDecision(review,{councilId:'co-freeze',analystReviewId:'a',asOf:'2026-09-21T05:00:00Z',methodVersion:'1',promptVersion:'1',specialistReviews:members,redTeamChallenges:[],stance:'NEUTRAL',confidence:.5,synthesis:'mixed',unresolvedDisagreements:[]}); members.length=0; assert.equal(out.specialistReviews.length,1); assert.equal(Object.isFrozen(out.specialistReviews),true); assert.throws(()=>createResearchCouncilDecision(review,{councilId:'co-bad-stance',analystReviewId:'a',asOf:'2026-09-21T05:00:00Z',methodVersion:'1',promptVersion:'1',specialistReviews:[sp],redTeamChallenges:[],stance:'NOT_A_STANCE' as any,confidence:.5,synthesis:'x',unresolvedDisagreements:[]}),/unsupported council stance/); });
