import assert from 'node:assert/strict'; import test from 'node:test';
import {createEvidencePacket,fingerprintCanonicalContent} from './evidence.js';
import {createResearchBundle,createAnalystReview} from './researchPipeline.js';
import {createResearchCouncilDecision} from './researchCouncil.js';
import {createThesisScenarioArtifact} from './thesisScenario.js';
const now=new Date('2026-09-21T06:00:00Z');
function setup(stance:'NEUTRAL'|'INSUFFICIENT_DATA'='NEUTRAL'){const mk=(id:string,txt:string)=>createEvidencePacket({evidenceId:id,source:{sourceId:id,sourceVersion:'v1',publisher:'T'},asset:{status:'RESOLVED',canonicalAssetId:'KRX:1',symbol:'1'},provenance:{retrievalUri:`https://example.test/${id}`,retrievedBy:'test'},publishedAt:'2026-09-21T04:00:00Z',observedAt:'2026-09-21T04:10:00Z',canonicalContent:txt},now);const mat=(id:string,txt:string)=>({evidenceId:id,canonicalContent:txt,contentFingerprint:fingerprintCanonicalContent(txt)});const bundle=createResearchBundle({bundleId:'b',subjectId:'KRX:1',asOf:'2026-09-21T04:30:00Z',knowledgeCutoff:'2026-09-21T04:30:00Z',items:[{evidence:mk('s','Demand improved.'),disposition:'SUPPORTING',material:mat('s','Demand improved.')},{evidence:mk('c','Margins weakened.'),disposition:'CONTRADICTING',material:mat('c','Margins weakened.')}],dataGaps:['GAP0']});const review=createAnalystReview(bundle,{reviewId:'a',bundleId:'b',analyst:{analystId:'a',role:'Analyst',domain:'company',methodVersion:'1',promptVersion:'1'},asOf:'2026-09-21T04:40:00Z',stance,confidence:stance==='INSUFFICIENT_DATA'?null:.5,assessment:'mixed',facts:[],inferences:[],assumptions:[],supportingEvidenceIds:['s'],counterevidenceIds:['c'],dataGaps:[],strongestCounterargument:'margin',invalidationConditions:[]});const council=createResearchCouncilDecision(review,{councilId:'co',analystReviewId:'a',asOf:'2026-09-21T05:00:00Z',methodVersion:'1',promptVersion:'1',specialistReviews:[],redTeamChallenges:[],stance:'INSUFFICIENT_DATA',confidence:null,synthesis:'bounded',unresolvedDisagreements:['demand vs margin'],dataGaps:['GAP1']});return{bundle,review,council};}
const scenarios=[{kind:'BULL' as const,narrative:'upside',evidenceIds:['s'],contradictingEvidenceIds:['c'],catalysts:['demand'],risks:['margin'],invalidationConditions:['demand reversal']},{kind:'BASE' as const,narrative:'mixed',evidenceIds:['s'],contradictingEvidenceIds:['c'],catalysts:[],risks:['margin'],invalidationConditions:['material change']},{kind:'BEAR' as const,narrative:'downside',evidenceIds:['c'],contradictingEvidenceIds:['c'],catalysts:[],risks:['margin'],invalidationConditions:['margin recovery']}];
function input(thesis=''){return{artifactId:'t1',bundleId:'b',analystReviewId:'a',councilId:'co',asOf:'2026-09-21T05:10:00Z',methodVersion:'1',thesis,scenarios};}
test('creates immutable three-scenario artifact preserving uncertainty and no authority',()=>{const {bundle,review,council}=setup();const out=createThesisScenarioArtifact(bundle,review,council,input());assert.equal(out.scenarios.length,3);assert.deepEqual(out.dataGaps,['GAP0','GAP1']);assert.deepEqual(out.unresolvedDisagreements,['demand vs margin']);assert.equal(out.executionAuthority,false);assert.equal(out.reportPublicationAuthority,false);assert.equal(Object.isFrozen(out.scenarios),true);});
test('fails closed on authority, chronology, cardinality and invented citations',()=>{const {bundle,review,council}=setup();assert.throws(()=>createThesisScenarioArtifact(bundle,review,council,{...input(),executionAuthority:true}),/cannot grant/);assert.throws(()=>createThesisScenarioArtifact(bundle,review,council,{...input(),asOf:'2026-09-21T04:50:00Z'}),/precede/);assert.throws(()=>createThesisScenarioArtifact(bundle,review,council,{...input(),scenarios:scenarios.slice(0,2)}),/exactly three/);const forged=[{...scenarios[0],evidenceIds:['invented']},scenarios[1],scenarios[2]];assert.throws(()=>createThesisScenarioArtifact(bundle,review,council,{...input(),scenarios:forged}),/outside/);});
test('rejects duplicate scenario kinds, wrong contradicting disposition and thesis laundering from insufficient data',()=>{const {bundle,review,council}=setup();assert.throws(()=>createThesisScenarioArtifact(bundle,review,council,{...input(),scenarios:[scenarios[0],{...scenarios[1],kind:'BULL'},scenarios[2]]}),/exactly one/);assert.throws(()=>createThesisScenarioArtifact(bundle,review,council,{...input(),scenarios:[{...scenarios[0],contradictingEvidenceIds:['s']},scenarios[1],scenarios[2]]}),/CONTRADICTING/);assert.throws(()=>createThesisScenarioArtifact(bundle,review,council,input('directional thesis')),/cannot produce/);});
